apiVersion: v1
kind: Service
metadata:
  name: download-gateway
  namespace: stube
  labels:
    app: download-gateway
spec:
  type: ClusterIP
  selector:
    app: download-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
